### ISSUE TITLE
Issue with yellow box when green version exists.

### ISSUE THREAD

**Issue by JaredIsaacs** [petergeorgas/Wordle-Api#3]
![image](https://github.com/petergeorgas/Wordle-API/assets/45950689/7c19e42e-4589-438d-b96b-659e18671918)

pls fix

**Comment by LoneWolfPR** [comment]
Just ran into this myself. Just curious if this is being worked on yet?

**Comment by JaredIsaacs** [comment]
I posted this on the wrong thing and didn’t realize.
